services:
  analyzer:
    build: .
    image: legitrum/analyzer:latest
    env_file:
      - .env.secrets
    environment:
      - LEGITRUM_SERVER=${LEGITRUM_SERVER:-https://legitrum.com}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ${PROJECT_PATH:-.}:/repo:ro
    restart: "no"
