services:
  analyzer:
    build: .
    image: legitrum/analyzer:latest
    env_file:
      - path: .env.secrets
        required: false
    environment:
      - LEGITRUM_TOKEN=${LEGITRUM_TOKEN}
      - LEGITRUM_SERVER=${LEGITRUM_SERVER:-https://legitrum.com}
      - ASSESSMENT_ID=${ASSESSMENT_ID}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ${PROJECT_PATH:-.}:/repo:ro
    restart: "no"
